import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const toolsDirectory = dirname(fileURLToPath(import.meta.url));
const root = join(toolsDirectory, "..");
const siteOrigin = "https://xynapse.online/clickntranslate";

const languageNames = {
  en: "English",
  ru: "Русский",
  es: "Español",
  de: "Deutsch",
  fr: "Français",
  "zh-CN": "中文",
};

const translations = {
  es: [
    ["Free Screen Translator for Windows | Click'n'Translate", "Traductor de pantalla gratuito para Windows | Click'n'Translate"],
    ["Copy or translate text from games, images, videos, apps, and documents. Free open-source screen OCR with hotkeys and online or offline engines.", "Copia o traduce texto de juegos, imágenes, vídeos, aplicaciones y documentos. OCR de pantalla gratuito y de código abierto con atajos y motores en línea o sin conexión."],
    ["Translate any text on your screen with one hotkey", "Traduce cualquier texto de la pantalla con un atajo"],
    ["Free, open-source screen OCR and translation for Windows and Linux.", "OCR y traducción de pantalla gratuitos y de código abierto para Windows y Linux."],
    ["Free open-source screen OCR and translation for Windows and Linux with configurable hotkeys and online or offline engines.", "OCR y traducción de pantalla gratuitos y de código abierto para Windows y Linux, con atajos configurables y motores en línea o sin conexión."],
    ["Skip to content", "Saltar al contenido"],
    ["Click'n'Translate home", "Inicio de Click'n'Translate"],
    ["Main navigation", "Navegación principal"],
    ["Workflows", "Modos"], ["Engines", "Motores"], ["Privacy", "Privacidad"], ["FAQ", "Preguntas"],
    ["Free and open source · Windows & Linux", "Gratis y de código abierto · Windows y Linux"],
    ["Translate any text <em>on your screen.</em>", "Traduce cualquier texto <em>directamente desde la pantalla.</em>"],
    ["Copy text that cannot be selected. Translate a game, image, video, application, or document. One hotkey keeps you in the flow.", "Copia texto que no se puede seleccionar. Traduce un juego, una imagen, un vídeo, una aplicación o un documento. Un solo atajo te permite continuar sin interrupciones."],
    ["Download the latest Windows version", "Descargar la última versión para Windows"],
    ["Other downloads", "Otras descargas"],
    ["Latest:", "Última versión:"], ["current release", "versión actual"], ["No account · No ads", "Sin cuenta · Sin anuncios"],
    ["Product facts", "Datos del producto"], ["global actions", "acciones globales"], ["local OCR engines", "motores OCR locales"], ["release downloads", "descargas de versiones"],
    ["Selecting dialogue in a game and showing its translation with Click'n'Translate", "Selección de un diálogo de juego y visualización de su traducción con Click'n'Translate"],
    ["Game translation", "Traducción en juegos"], ["Real recording from Click'n'Translate", "Grabación real de Click'n'Translate"],
    ["Key benefits", "Ventajas principales"], ["OCR stays on your computer", "El OCR permanece en tu equipo"], ["Online or offline translation", "Traducción en línea o sin conexión"], ["Configurable hotkeys", "Atajos configurables"], ["Source code on GitHub", "Código fuente en GitHub"],
    ["Real application recordings", "Grabaciones reales de la aplicación"], ["See the workflows in action.", "Mira cómo funcionan los modos."], ["Every animation below is captured from Click'n'Translate itself — no generated interface mockups.", "Todas las animaciones se grabaron directamente en Click'n'Translate, sin maquetas de interfaz generadas."],
    ["Selecting a screen area and copying its recognized text with OCR", "Selección de un área de la pantalla y copia del texto reconocido mediante OCR"], ["Area OCR", "OCR de área"], ["Copy text from any screen region.", "Copia texto de cualquier zona de la pantalla."],
    ["Translating highlighted text inside a desktop application", "Traducción de texto seleccionado dentro de una aplicación de escritorio"], ["Selected text", "Texto seleccionado"], ["Translate a selection without changing apps.", "Traduce una selección sin cambiar de aplicación."],
    ["Replacing text across the screen with translated overlays", "Sustitución del texto de la pantalla por capas traducidas"], ["Full-screen translation", "Traducción de pantalla completa"], ["Translate the visible screen with one hotkey.", "Traduce la pantalla visible con un atajo."],
    ["Downloading and installing a Click'n'Translate update inside the app", "Descarga e instalación de una actualización de Click'n'Translate desde la aplicación"], ["In-app updates", "Actualizaciones integradas"], ["Install the latest public release from the app.", "Instala la última versión pública desde la aplicación."],
    ["One app, several jobs", "Una aplicación, varias tareas"], ["Text becomes useful the moment you see it.", "El texto se vuelve útil en cuanto lo ves."], ["Choose the result you need instead of moving the same screenshot through several utilities.", "Elige el resultado que necesitas sin pasar la misma captura por varias herramientas."],
    ["Dynamic translation", "Traducción dinámica"], ["Select one or several regions. Unchanged frames are skipped; translated overlays update only when the source text changes.", "Selecciona una o varias zonas. Los fotogramas sin cambios se omiten y las capas traducidas se actualizan solo cuando cambia el texto original."],
    ["Copy text from images, videos, games, scans, and interfaces that block selection.", "Copia texto de imágenes, vídeos, juegos, documentos escaneados e interfaces que impiden seleccionarlo."],
    ["Screen translation", "Traducción de pantalla"], ["Translate one focused area or place translated text over the entire screen.", "Traduce un área concreta o coloca el texto traducido sobre toda la pantalla."],
    ["Translate a selection or replace it in the same application with the saved language pair.", "Traduce una selección o sustitúyela en la misma aplicación con el par de idiomas guardado."],
    ["Documents", "Documentos"], ["Open common text, Word, PDF, HTML, and RTF files with original and translation side by side.", "Abre archivos de texto, Word, PDF, HTML y RTF con el original y la traducción uno al lado del otro."],
    ["Your screen, your route", "Tu pantalla, tu método"], ["Use the engine that fits the text.", "Usa el motor que mejor se adapte al texto."], ["Stylized fonts, scripts, scaling, and poor contrast behave differently. Install only the components you need.", "Las fuentes decorativas, los alfabetos, el escalado y el bajo contraste se comportan de forma distinta. Instala solo los componentes que necesites."],
    ["Local OCR", "OCR local"], ["On device", "En el dispositivo"], ["Online translation", "Traducción en línea"], ["Internet", "Internet"], ["Offline translation", "Traducción sin conexión"],
    ["Privacy without vague promises", "Privacidad sin promesas ambiguas"], ["Know where your text goes.", "Sabe siempre adónde va tu texto."],
    ["OCR runs locally. Argos Translate and Hy-MT also translate locally after their packages are installed. If you choose an online provider, the text you request to translate is sent to that provider.", "El OCR se ejecuta de forma local. Argos Translate y Hy-MT también traducen localmente tras instalar sus paquetes. Si eliges un proveedor en línea, se le envía el texto que has solicitado traducir."],
    ["Copy and translation histories stay on your computer and are optional. The app includes no developer-operated analytics.", "Los historiales de copia y traducción son opcionales y permanecen en tu equipo. La aplicación no incluye analíticas gestionadas por el desarrollador."], ["Read the privacy policy →", "Leer la política de privacidad →"],
    ["Built in public", "Desarrollado en público"], ["Free software with visible trade-offs.", "Software libre con límites transparentes."], ["Source, issues, and release history are public.", "El código, los problemas y el historial de versiones son públicos."], ["Automated checks in the current repository.", "Comprobaciones automatizadas en el repositorio actual."], ["Safe reports", "Informes seguros"], ["Diagnostics exclude clipboard text, documents, histories, credentials, and OCR logs.", "Los diagnósticos excluyen el texto del portapapeles, documentos, historiales, credenciales y registros OCR."],
    ["About Windows antivirus warnings", "Sobre los avisos del antivirus en Windows"], ["The Windows build is currently unsigned. Global hotkeys, screen capture, clipboard integration, optional autostart, and updating can trigger generic heuristic warnings. Download only from the official repository, verify release hashes, and report unexpected detections so they can be investigated.", "La compilación para Windows todavía no está firmada. Los atajos globales, la captura de pantalla, la integración con el portapapeles, el inicio automático opcional y las actualizaciones pueden activar avisos heurísticos genéricos. Descarga únicamente desde el repositorio oficial, comprueba los hashes y comunica cualquier detección inesperada para investigarla."],
    ["Questions, answered", "Respuestas rápidas"], ["Before you install.", "Antes de instalar."],
    ["Does it work offline?", "¿Funciona sin conexión?"], ["Yes, after installing the OCR language data and an Argos Translate or Hy-MT package for the direction you need. Online providers still require a connection.", "Sí, después de instalar los datos de idioma OCR y un paquete de Argos Translate o Hy-MT para la dirección que necesites. Los proveedores en línea siguen requiriendo conexión."],
    ["Can it translate games and videos?", "¿Puede traducir juegos y vídeos?"], ["Yes. OCR reads pixels from a selected region, so the source does not have to be selectable. Accuracy depends on the language, font, scale, contrast, and selected OCR engine.", "Sí. El OCR lee los píxeles de la zona seleccionada, así que el texto original no tiene que poder seleccionarse. La precisión depende del idioma, la fuente, la escala, el contraste y el motor OCR elegido."],
    ["Does it support Linux?", "¿Es compatible con Linux?"], ["Yes. The release page provides an x86_64 AppImage and a portable TAR archive. Screen capture integration may vary by desktop session.", "Sí. La página de versiones ofrece una AppImage x86_64 y un archivo TAR portátil. La integración de captura puede variar según la sesión de escritorio."],
    ["Can I change every hotkey?", "¿Puedo cambiar todos los atajos?"], ["Yes. Every global shortcut can be changed or cleared. OCR, full-screen, selection, replacement, and Dynamic translation remember their own language pair.", "Sí. Todos los atajos globales se pueden cambiar o borrar. OCR, pantalla completa, selección, sustitución y traducción dinámica recuerdan su propio par de idiomas."],
    ["What document formats are supported?", "¿Qué formatos de documento admite?"], ["TXT, Markdown, DOCX, PDF, HTML, HTM, and RTF. Results can be saved as text, Markdown, or a reopenable local session.", "TXT, Markdown, DOCX, PDF, HTML, HTM y RTF. Los resultados se pueden guardar como texto, Markdown o una sesión local que se puede volver a abrir."],
    ["See it. Select it. Understand it.", "Míralo. Selecciónalo. Entiéndelo."], ["Translate the first thing that gets in your way.", "Traduce lo primero que se interponga en tu camino."], ["Download the latest Click'n'Translate", "Descargar la última versión de Click'n'Translate"], ["Browse the source", "Ver el código fuente"],
    ["Free and open-source screen OCR and translation.", "OCR y traducción de pantalla gratuitos y de código abierto."], ["Footer navigation", "Navegación del pie"], ["Downloads", "Descargas"], ["Bug reports", "Informes de errores"], ["License", "Licencia"],
  ],
  de: [
    ["Free Screen Translator for Windows | Click'n'Translate", "Kostenloser Bildschirmübersetzer für Windows | Click'n'Translate"],
    ["Copy or translate text from games, images, videos, apps, and documents. Free open-source screen OCR with hotkeys and online or offline engines.", "Text aus Spielen, Bildern, Videos, Anwendungen und Dokumenten kopieren oder übersetzen. Kostenlose Open-Source-Bildschirm-OCR mit Hotkeys sowie Online- und Offline-Engines."],
    ["Translate any text on your screen with one hotkey", "Beliebigen Bildschirmtext mit einem Hotkey übersetzen"],
    ["Free, open-source screen OCR and translation for Windows and Linux.", "Kostenlose Open-Source-Bildschirm-OCR und Übersetzung für Windows und Linux."],
    ["Free open-source screen OCR and translation for Windows and Linux with configurable hotkeys and online or offline engines.", "Kostenlose Open-Source-Bildschirm-OCR und Übersetzung für Windows und Linux mit konfigurierbaren Hotkeys sowie Online- und Offline-Engines."],
    ["Skip to content", "Zum Inhalt springen"], ["Click'n'Translate home", "Click'n'Translate Startseite"], ["Main navigation", "Hauptnavigation"],
    ["Workflows", "Modi"], ["Engines", "Engines"], ["Privacy", "Datenschutz"], ["FAQ", "FAQ"],
    ["Free and open source · Windows & Linux", "Kostenlos und quelloffen · Windows & Linux"],
    ["Translate any text <em>on your screen.</em>", "Übersetze jeden Text <em>direkt auf deinem Bildschirm.</em>"],
    ["Copy text that cannot be selected. Translate a game, image, video, application, or document. One hotkey keeps you in the flow.", "Kopiere Text, der sich nicht markieren lässt. Übersetze Spiele, Bilder, Videos, Anwendungen oder Dokumente. Ein Hotkey hält dich im Arbeitsfluss."],
    ["Download the latest Windows version", "Neueste Windows-Version herunterladen"], ["Other downloads", "Weitere Downloads"], ["Latest:", "Neueste Version:"], ["current release", "aktuelles Release"], ["No account · No ads", "Kein Konto · Keine Werbung"],
    ["Product facts", "Produktdaten"], ["global actions", "globale Aktionen"], ["local OCR engines", "lokale OCR-Engines"], ["release downloads", "Release-Downloads"],
    ["Selecting dialogue in a game and showing its translation with Click'n'Translate", "Dialog in einem Spiel auswählen und mit Click'n'Translate übersetzen"], ["Game translation", "Spielübersetzung"], ["Real recording from Click'n'Translate", "Echte Aufnahme aus Click'n'Translate"],
    ["Key benefits", "Wichtigste Vorteile"], ["OCR stays on your computer", "OCR bleibt auf deinem Computer"], ["Online or offline translation", "Online- oder Offline-Übersetzung"], ["Configurable hotkeys", "Konfigurierbare Hotkeys"], ["Source code on GitHub", "Quellcode auf GitHub"],
    ["Real application recordings", "Echte Programmaufnahmen"], ["See the workflows in action.", "Sieh dir die Modi in Aktion an."], ["Every animation below is captured from Click'n'Translate itself — no generated interface mockups.", "Jede Animation wurde direkt in Click'n'Translate aufgenommen – ohne generierte Oberflächen-Mockups."],
    ["Selecting a screen area and copying its recognized text with OCR", "Bildschirmbereich auswählen und den erkannten Text per OCR kopieren"], ["Area OCR", "Bereichs-OCR"], ["Copy text from any screen region.", "Text aus jedem Bildschirmbereich kopieren."],
    ["Translating highlighted text inside a desktop application", "Markierten Text in einer Desktop-Anwendung übersetzen"], ["Selected text", "Markierter Text"], ["Translate a selection without changing apps.", "Eine Auswahl übersetzen, ohne die Anwendung zu wechseln."],
    ["Replacing text across the screen with translated overlays", "Bildschirmtext durch übersetzte Einblendungen ersetzen"], ["Full-screen translation", "Vollbildübersetzung"], ["Translate the visible screen with one hotkey.", "Den sichtbaren Bildschirm mit einem Hotkey übersetzen."],
    ["Downloading and installing a Click'n'Translate update inside the app", "Ein Click'n'Translate-Update direkt in der Anwendung herunterladen und installieren"], ["In-app updates", "Updates in der App"], ["Install the latest public release from the app.", "Das neueste öffentliche Release direkt aus der App installieren."],
    ["One app, several jobs", "Eine App, mehrere Aufgaben"], ["Text becomes useful the moment you see it.", "Text wird nutzbar, sobald du ihn siehst."], ["Choose the result you need instead of moving the same screenshot through several utilities.", "Wähle direkt das gewünschte Ergebnis, statt denselben Screenshot durch mehrere Programme zu schicken."],
    ["Dynamic translation", "Dynamische Übersetzung"], ["Select one or several regions. Unchanged frames are skipped; translated overlays update only when the source text changes.", "Wähle einen oder mehrere Bereiche. Unveränderte Bilder werden übersprungen; die Übersetzung wird nur aktualisiert, wenn sich der Ausgangstext ändert."],
    ["Copy text from images, videos, games, scans, and interfaces that block selection.", "Kopiere Text aus Bildern, Videos, Spielen, Scans und Oberflächen, die keine Auswahl zulassen."], ["Screen translation", "Bildschirmübersetzung"], ["Translate one focused area or place translated text over the entire screen.", "Übersetze einen bestimmten Bereich oder blende die Übersetzung über dem gesamten Bildschirm ein."], ["Translate a selection or replace it in the same application with the saved language pair.", "Übersetze eine Auswahl oder ersetze sie in derselben Anwendung mit dem gespeicherten Sprachpaar."],
    ["Documents", "Dokumente"], ["Open common text, Word, PDF, HTML, and RTF files with original and translation side by side.", "Öffne gängige Text-, Word-, PDF-, HTML- und RTF-Dateien mit Original und Übersetzung nebeneinander."],
    ["Your screen, your route", "Dein Bildschirm, dein Weg"], ["Use the engine that fits the text.", "Nutze die Engine, die zum Text passt."], ["Stylized fonts, scripts, scaling, and poor contrast behave differently. Install only the components you need.", "Stilisierte Schriften, Schriftsysteme, Skalierung und geringer Kontrast verhalten sich unterschiedlich. Installiere nur die Komponenten, die du brauchst."],
    ["Local OCR", "Lokale OCR"], ["On device", "Auf dem Gerät"], ["Online translation", "Online-Übersetzung"], ["Offline translation", "Offline-Übersetzung"],
    ["Privacy without vague promises", "Datenschutz ohne leere Versprechen"], ["Know where your text goes.", "Du weißt, wohin dein Text geht."], ["OCR runs locally. Argos Translate and Hy-MT also translate locally after their packages are installed. If you choose an online provider, the text you request to translate is sent to that provider.", "OCR läuft lokal. Nach der Paketinstallation übersetzen auch Argos Translate und Hy-MT lokal. Bei einem Online-Anbieter wird nur der Text übertragen, dessen Übersetzung du anforderst."], ["Copy and translation histories stay on your computer and are optional. The app includes no developer-operated analytics.", "Kopier- und Übersetzungsverläufe sind optional und bleiben auf deinem Computer. Die App enthält keine vom Entwickler betriebene Analyse."], ["Read the privacy policy →", "Datenschutzerklärung lesen →"],
    ["Built in public", "Offen entwickelt"], ["Free software with visible trade-offs.", "Freie Software mit transparenten Kompromissen."], ["Source, issues, and release history are public.", "Quellcode, Issues und Release-Verlauf sind öffentlich."], ["Automated checks in the current repository.", "Automatisierte Prüfungen im aktuellen Repository."], ["Safe reports", "Sichere Berichte"], ["Diagnostics exclude clipboard text, documents, histories, credentials, and OCR logs.", "Diagnosen schließen Zwischenablagetext, Dokumente, Verläufe, Zugangsdaten und OCR-Protokolle aus."],
    ["About Windows antivirus warnings", "Zu Antivirus-Warnungen unter Windows"], ["The Windows build is currently unsigned. Global hotkeys, screen capture, clipboard integration, optional autostart, and updating can trigger generic heuristic warnings. Download only from the official repository, verify release hashes, and report unexpected detections so they can be investigated.", "Die Windows-Version ist derzeit nicht signiert. Globale Hotkeys, Bildschirmaufnahme, Zwischenablage-Integration, optionaler Autostart und Updates können allgemeine heuristische Warnungen auslösen. Lade nur aus dem offiziellen Repository herunter, prüfe die Release-Hashes und melde unerwartete Erkennungen zur Untersuchung."],
    ["Questions, answered", "Kurze Antworten"], ["Before you install.", "Vor der Installation."], ["Does it work offline?", "Funktioniert es offline?"], ["Yes, after installing the OCR language data and an Argos Translate or Hy-MT package for the direction you need. Online providers still require a connection.", "Ja, nachdem du die OCR-Sprachdaten und ein Argos-Translate- oder Hy-MT-Paket für die gewünschte Richtung installiert hast. Online-Anbieter benötigen weiterhin eine Verbindung."],
    ["Can it translate games and videos?", "Kann es Spiele und Videos übersetzen?"], ["Yes. OCR reads pixels from a selected region, so the source does not have to be selectable. Accuracy depends on the language, font, scale, contrast, and selected OCR engine.", "Ja. OCR liest die Pixel eines ausgewählten Bereichs, daher muss der Ausgangstext nicht markierbar sein. Die Genauigkeit hängt von Sprache, Schrift, Skalierung, Kontrast und gewählter OCR-Engine ab."],
    ["Does it support Linux?", "Wird Linux unterstützt?"], ["Yes. The release page provides an x86_64 AppImage and a portable TAR archive. Screen capture integration may vary by desktop session.", "Ja. Auf der Release-Seite gibt es ein x86_64-AppImage und ein portables TAR-Archiv. Die Integration der Bildschirmaufnahme kann je nach Desktop-Sitzung variieren."],
    ["Can I change every hotkey?", "Kann ich jeden Hotkey ändern?"], ["Yes. Every global shortcut can be changed or cleared. OCR, full-screen, selection, replacement, and Dynamic translation remember their own language pair.", "Ja. Jeder globale Hotkey kann geändert oder entfernt werden. OCR, Vollbild, Auswahl, Ersetzen und dynamische Übersetzung speichern jeweils ihr eigenes Sprachpaar."],
    ["What document formats are supported?", "Welche Dokumentformate werden unterstützt?"], ["TXT, Markdown, DOCX, PDF, HTML, HTM, and RTF. Results can be saved as text, Markdown, or a reopenable local session.", "TXT, Markdown, DOCX, PDF, HTML, HTM und RTF. Ergebnisse können als Text, Markdown oder als erneut öffnbare lokale Sitzung gespeichert werden."],
    ["See it. Select it. Understand it.", "Sehen. Auswählen. Verstehen."], ["Translate the first thing that gets in your way.", "Übersetze den ersten Text, der dich aufhält."], ["Download the latest Click'n'Translate", "Neueste Click'n'Translate-Version herunterladen"], ["Browse the source", "Quellcode ansehen"], ["Free and open-source screen OCR and translation.", "Kostenlose Open-Source-Bildschirm-OCR und Übersetzung."], ["Footer navigation", "Navigation in der Fußzeile"], ["Downloads", "Downloads"], ["Bug reports", "Fehler melden"], ["License", "Lizenz"],
  ],
  fr: [
    ["Free Screen Translator for Windows | Click'n'Translate", "Traducteur d'écran gratuit pour Windows | Click'n'Translate"],
    ["Copy or translate text from games, images, videos, apps, and documents. Free open-source screen OCR with hotkeys and online or offline engines.", "Copiez ou traduisez le texte des jeux, images, vidéos, applications et documents. OCR d'écran gratuit et open source avec raccourcis et moteurs en ligne ou hors ligne."],
    ["Translate any text on your screen with one hotkey", "Traduisez n'importe quel texte à l'écran avec un raccourci"], ["Free, open-source screen OCR and translation for Windows and Linux.", "OCR et traduction d'écran gratuits et open source pour Windows et Linux."], ["Free open-source screen OCR and translation for Windows and Linux with configurable hotkeys and online or offline engines.", "OCR et traduction d'écran gratuits et open source pour Windows et Linux, avec raccourcis configurables et moteurs en ligne ou hors ligne."],
    ["Skip to content", "Aller au contenu"], ["Click'n'Translate home", "Accueil Click'n'Translate"], ["Main navigation", "Navigation principale"], ["Workflows", "Modes"], ["Engines", "Moteurs"], ["Privacy", "Confidentialité"], ["FAQ", "Questions"],
    ["Free and open source · Windows & Linux", "Gratuit et open source · Windows et Linux"], ["Translate any text <em>on your screen.</em>", "Traduisez n'importe quel texte <em>directement à l'écran.</em>"], ["Copy text that cannot be selected. Translate a game, image, video, application, or document. One hotkey keeps you in the flow.", "Copiez le texte impossible à sélectionner. Traduisez un jeu, une image, une vidéo, une application ou un document. Un seul raccourci vous permet de rester concentré."],
    ["Download the latest Windows version", "Télécharger la dernière version Windows"], ["Other downloads", "Autres téléchargements"], ["Latest:", "Dernière version :"], ["current release", "version actuelle"], ["No account · No ads", "Sans compte · Sans publicité"],
    ["Product facts", "Informations produit"], ["global actions", "actions globales"], ["local OCR engines", "moteurs OCR locaux"], ["release downloads", "téléchargements des versions"],
    ["Selecting dialogue in a game and showing its translation with Click'n'Translate", "Sélection d'un dialogue dans un jeu et affichage de sa traduction avec Click'n'Translate"], ["Game translation", "Traduction de jeu"], ["Real recording from Click'n'Translate", "Capture réelle de Click'n'Translate"],
    ["Key benefits", "Principaux avantages"], ["OCR stays on your computer", "L'OCR reste sur votre ordinateur"], ["Online or offline translation", "Traduction en ligne ou hors ligne"], ["Configurable hotkeys", "Raccourcis configurables"], ["Source code on GitHub", "Code source sur GitHub"],
    ["Real application recordings", "Captures réelles de l'application"], ["See the workflows in action.", "Découvrez les modes en action."], ["Every animation below is captured from Click'n'Translate itself — no generated interface mockups.", "Chaque animation ci-dessous a été capturée directement dans Click'n'Translate, sans maquette d'interface générée."],
    ["Selecting a screen area and copying its recognized text with OCR", "Sélection d'une zone de l'écran et copie du texte reconnu par OCR"], ["Area OCR", "OCR de zone"], ["Copy text from any screen region.", "Copiez le texte de n'importe quelle zone de l'écran."],
    ["Translating highlighted text inside a desktop application", "Traduction du texte sélectionné dans une application de bureau"], ["Selected text", "Texte sélectionné"], ["Translate a selection without changing apps.", "Traduisez une sélection sans changer d'application."],
    ["Replacing text across the screen with translated overlays", "Remplacement du texte à l'écran par des superpositions traduites"], ["Full-screen translation", "Traduction plein écran"], ["Translate the visible screen with one hotkey.", "Traduisez l'écran visible avec un raccourci."],
    ["Downloading and installing a Click'n'Translate update inside the app", "Téléchargement et installation d'une mise à jour Click'n'Translate dans l'application"], ["In-app updates", "Mises à jour intégrées"], ["Install the latest public release from the app.", "Installez la dernière version publique depuis l'application."],
    ["One app, several jobs", "Une application, plusieurs usages"], ["Text becomes useful the moment you see it.", "Le texte devient exploitable dès que vous le voyez."], ["Choose the result you need instead of moving the same screenshot through several utilities.", "Choisissez directement le résultat souhaité au lieu de faire passer la même capture par plusieurs outils."],
    ["Dynamic translation", "Traduction dynamique"], ["Select one or several regions. Unchanged frames are skipped; translated overlays update only when the source text changes.", "Sélectionnez une ou plusieurs zones. Les images inchangées sont ignorées et les superpositions ne se mettent à jour que lorsque le texte source change."],
    ["Copy text from images, videos, games, scans, and interfaces that block selection.", "Copiez du texte depuis des images, vidéos, jeux, scans et interfaces qui empêchent la sélection."], ["Screen translation", "Traduction de l'écran"], ["Translate one focused area or place translated text over the entire screen.", "Traduisez une zone précise ou affichez le texte traduit sur l'ensemble de l'écran."], ["Translate a selection or replace it in the same application with the saved language pair.", "Traduisez une sélection ou remplacez-la dans la même application avec la paire de langues enregistrée."],
    ["Documents", "Documents"], ["Open common text, Word, PDF, HTML, and RTF files with original and translation side by side.", "Ouvrez les fichiers texte, Word, PDF, HTML et RTF courants avec l'original et la traduction côte à côte."],
    ["Your screen, your route", "Votre écran, votre méthode"], ["Use the engine that fits the text.", "Utilisez le moteur adapté au texte."], ["Stylized fonts, scripts, scaling, and poor contrast behave differently. Install only the components you need.", "Les polices stylisées, les systèmes d'écriture, la mise à l'échelle et le faible contraste se comportent différemment. Installez uniquement les composants nécessaires."],
    ["Local OCR", "OCR local"], ["On device", "Sur l'appareil"], ["Online translation", "Traduction en ligne"], ["Offline translation", "Traduction hors ligne"],
    ["Privacy without vague promises", "Une confidentialité sans promesses vagues"], ["Know where your text goes.", "Sachez toujours où va votre texte."], ["OCR runs locally. Argos Translate and Hy-MT also translate locally after their packages are installed. If you choose an online provider, the text you request to translate is sent to that provider.", "L'OCR s'exécute localement. Argos Translate et Hy-MT traduisent également en local après installation de leurs paquets. Si vous choisissez un fournisseur en ligne, seul le texte demandé lui est envoyé."], ["Copy and translation histories stay on your computer and are optional. The app includes no developer-operated analytics.", "Les historiques de copie et de traduction sont facultatifs et restent sur votre ordinateur. L'application ne contient aucune analyse gérée par le développeur."], ["Read the privacy policy →", "Lire la politique de confidentialité →"],
    ["Built in public", "Développé publiquement"], ["Free software with visible trade-offs.", "Un logiciel libre aux compromis transparents."], ["Source, issues, and release history are public.", "Le code source, les problèmes et l'historique des versions sont publics."], ["Automated checks in the current repository.", "Vérifications automatisées dans le dépôt actuel."], ["Safe reports", "Rapports sûrs"], ["Diagnostics exclude clipboard text, documents, histories, credentials, and OCR logs.", "Les diagnostics excluent le texte du presse-papiers, les documents, les historiques, les identifiants et les journaux OCR."],
    ["About Windows antivirus warnings", "À propos des alertes antivirus sous Windows"], ["The Windows build is currently unsigned. Global hotkeys, screen capture, clipboard integration, optional autostart, and updating can trigger generic heuristic warnings. Download only from the official repository, verify release hashes, and report unexpected detections so they can be investigated.", "La version Windows n'est pas encore signée. Les raccourcis globaux, la capture d'écran, l'intégration au presse-papiers, le démarrage automatique facultatif et les mises à jour peuvent déclencher des alertes heuristiques génériques. Téléchargez uniquement depuis le dépôt officiel, vérifiez les empreintes des versions et signalez toute détection inattendue afin qu'elle soit examinée."],
    ["Questions, answered", "Réponses rapides"], ["Before you install.", "Avant l'installation."], ["Does it work offline?", "Fonctionne-t-il hors ligne ?"], ["Yes, after installing the OCR language data and an Argos Translate or Hy-MT package for the direction you need. Online providers still require a connection.", "Oui, après avoir installé les données de langue OCR et un paquet Argos Translate ou Hy-MT pour la direction souhaitée. Les fournisseurs en ligne nécessitent toujours une connexion."],
    ["Can it translate games and videos?", "Peut-il traduire les jeux et les vidéos ?"], ["Yes. OCR reads pixels from a selected region, so the source does not have to be selectable. Accuracy depends on the language, font, scale, contrast, and selected OCR engine.", "Oui. L'OCR lit les pixels de la zone sélectionnée : le texte source n'a donc pas besoin d'être sélectionnable. La précision dépend de la langue, de la police, de l'échelle, du contraste et du moteur OCR choisi."],
    ["Does it support Linux?", "Linux est-il pris en charge ?"], ["Yes. The release page provides an x86_64 AppImage and a portable TAR archive. Screen capture integration may vary by desktop session.", "Oui. La page des versions propose une AppImage x86_64 et une archive TAR portable. L'intégration de la capture d'écran peut varier selon la session de bureau."],
    ["Can I change every hotkey?", "Puis-je modifier tous les raccourcis ?"], ["Yes. Every global shortcut can be changed or cleared. OCR, full-screen, selection, replacement, and Dynamic translation remember their own language pair.", "Oui. Chaque raccourci global peut être modifié ou supprimé. L'OCR, le plein écran, la sélection, le remplacement et la traduction dynamique mémorisent chacun leur propre paire de langues."],
    ["What document formats are supported?", "Quels formats de document sont pris en charge ?"], ["TXT, Markdown, DOCX, PDF, HTML, HTM, and RTF. Results can be saved as text, Markdown, or a reopenable local session.", "TXT, Markdown, DOCX, PDF, HTML, HTM et RTF. Les résultats peuvent être enregistrés en texte, en Markdown ou dans une session locale à rouvrir."],
    ["See it. Select it. Understand it.", "Voyez. Sélectionnez. Comprenez."], ["Translate the first thing that gets in your way.", "Traduisez le premier texte qui vous bloque."], ["Download the latest Click'n'Translate", "Télécharger la dernière version de Click'n'Translate"], ["Browse the source", "Voir le code source"], ["Free and open-source screen OCR and translation.", "OCR et traduction d'écran gratuits et open source."], ["Footer navigation", "Navigation du pied de page"], ["Downloads", "Téléchargements"], ["Bug reports", "Signaler un bug"], ["License", "Licence"],
  ],
  "zh-CN": [
    ["Free Screen Translator for Windows | Click'n'Translate", "Windows 免费屏幕翻译工具 | Click'n'Translate"],
    ["Copy or translate text from games, images, videos, apps, and documents. Free open-source screen OCR with hotkeys and online or offline engines.", "复制或翻译游戏、图片、视频、应用和文档中的文字。免费开源的屏幕 OCR，支持快捷键以及在线或离线引擎。"],
    ["Translate any text on your screen with one hotkey", "一个快捷键翻译屏幕上的任意文字"], ["Free, open-source screen OCR and translation for Windows and Linux.", "适用于 Windows 和 Linux 的免费开源屏幕 OCR 与翻译工具。"], ["Free open-source screen OCR and translation for Windows and Linux with configurable hotkeys and online or offline engines.", "适用于 Windows 和 Linux 的免费开源屏幕 OCR 与翻译工具，支持自定义快捷键以及在线或离线引擎。"],
    ["Skip to content", "跳到正文"], ["Click'n'Translate home", "Click'n'Translate 首页"], ["Main navigation", "主导航"], ["Workflows", "模式"], ["Engines", "引擎"], ["Privacy", "隐私"], ["FAQ", "常见问题"],
    ["Free and open source · Windows & Linux", "免费开源 · Windows 与 Linux"], ["Translate any text <em>on your screen.</em>", "翻译任意文字，<em>就在你的屏幕上。</em>"], ["Copy text that cannot be selected. Translate a game, image, video, application, or document. One hotkey keeps you in the flow.", "复制无法选中的文字。翻译游戏、图片、视频、应用或文档。只需一个快捷键，不打断当前操作。"],
    ["Download the latest Windows version", "下载最新版 Windows 程序"], ["Other downloads", "其他下载"], ["Latest:", "最新版本："], ["current release", "当前版本"], ["No account · No ads", "无需账户 · 无广告"],
    ["Product facts", "产品信息"], ["global actions", "全局操作"], ["local OCR engines", "本地 OCR 引擎"], ["release downloads", "版本下载量"],
    ["Selecting dialogue in a game and showing its translation with Click'n'Translate", "在游戏中选取对话并使用 Click'n'Translate 显示翻译"], ["Game translation", "游戏翻译"], ["Real recording from Click'n'Translate", "Click'n'Translate 真实录屏"],
    ["Key benefits", "核心优势"], ["OCR stays on your computer", "OCR 始终在本机运行"], ["Online or offline translation", "在线或离线翻译"], ["Configurable hotkeys", "可自定义快捷键"], ["Source code on GitHub", "GitHub 上的源代码"],
    ["Real application recordings", "真实程序录屏"], ["See the workflows in action.", "查看各模式的实际效果。"], ["Every animation below is captured from Click'n'Translate itself — no generated interface mockups.", "下方每段动画均直接录制自 Click'n'Translate，没有生成的界面示意图。"],
    ["Selecting a screen area and copying its recognized text with OCR", "选择屏幕区域并复制 OCR 识别出的文字"], ["Area OCR", "区域 OCR"], ["Copy text from any screen region.", "复制屏幕任意区域中的文字。"],
    ["Translating highlighted text inside a desktop application", "在桌面应用中翻译选中的文字"], ["Selected text", "选中文字"], ["Translate a selection without changing apps.", "无需切换应用即可翻译选中内容。"],
    ["Replacing text across the screen with translated overlays", "用翻译浮层替换屏幕上的文字"], ["Full-screen translation", "全屏翻译"], ["Translate the visible screen with one hotkey.", "一个快捷键翻译当前屏幕。"],
    ["Downloading and installing a Click'n'Translate update inside the app", "在应用内下载并安装 Click'n'Translate 更新"], ["In-app updates", "应用内更新"], ["Install the latest public release from the app.", "直接在应用内安装最新公开版本。"],
    ["One app, several jobs", "一个应用，多种用途"], ["Text becomes useful the moment you see it.", "看到文字的那一刻，它就能为你所用。"], ["Choose the result you need instead of moving the same screenshot through several utilities.", "直接选择所需结果，无需在多个工具之间反复传递同一张截图。"],
    ["Dynamic translation", "动态翻译"], ["Select one or several regions. Unchanged frames are skipped; translated overlays update only when the source text changes.", "选择一个或多个区域。画面未变化时会跳过处理；只有原文发生变化时，翻译浮层才会更新。"],
    ["Copy text from images, videos, games, scans, and interfaces that block selection.", "从图片、视频、游戏、扫描件及无法选中文字的界面中复制文本。"], ["Screen translation", "屏幕翻译"], ["Translate one focused area or place translated text over the entire screen.", "翻译指定区域，或将译文覆盖到整个屏幕。"], ["Translate a selection or replace it in the same application with the saved language pair.", "使用已保存的语言对翻译选中内容，或在原应用中直接替换。"],
    ["Documents", "文档"], ["Open common text, Word, PDF, HTML, and RTF files with original and translation side by side.", "打开常见文本、Word、PDF、HTML 和 RTF 文件，并排查看原文与译文。"],
    ["Your screen, your route", "你的屏幕，你的方案"], ["Use the engine that fits the text.", "选择最适合当前文字的引擎。"], ["Stylized fonts, scripts, scaling, and poor contrast behave differently. Install only the components you need.", "艺术字体、不同文字体系、缩放和低对比度会带来不同效果。只安装你需要的组件。"],
    ["Local OCR", "本地 OCR"], ["On device", "本机"], ["Online translation", "在线翻译"], ["Internet", "联网"], ["Offline translation", "离线翻译"],
    ["Privacy without vague promises", "隐私承诺清晰明确"], ["Know where your text goes.", "清楚了解文字会发送到哪里。"], ["OCR runs locally. Argos Translate and Hy-MT also translate locally after their packages are installed. If you choose an online provider, the text you request to translate is sent to that provider.", "OCR 在本机运行。安装相应语言包后，Argos Translate 和 Hy-MT 也会在本机翻译。如果选择在线服务商，你请求翻译的文字将发送给该服务商。"], ["Copy and translation histories stay on your computer and are optional. The app includes no developer-operated analytics.", "复制与翻译历史为可选功能，并保存在你的电脑上。应用不包含开发者运营的数据分析。"], ["Read the privacy policy →", "阅读隐私政策 →"],
    ["Built in public", "公开开发"], ["Free software with visible trade-offs.", "限制透明的自由软件。"], ["Source, issues, and release history are public.", "源代码、问题和版本历史全部公开。"], ["Automated checks in the current repository.", "当前代码仓库中的自动化检查。"], ["Safe reports", "安全报告"], ["Diagnostics exclude clipboard text, documents, histories, credentials, and OCR logs.", "诊断报告不会包含剪贴板文字、文档、历史记录、凭据和 OCR 日志。"],
    ["About Windows antivirus warnings", "关于 Windows 杀毒软件警告"], ["The Windows build is currently unsigned. Global hotkeys, screen capture, clipboard integration, optional autostart, and updating can trigger generic heuristic warnings. Download only from the official repository, verify release hashes, and report unexpected detections so they can be investigated.", "Windows 版本目前尚未进行代码签名。全局快捷键、屏幕捕获、剪贴板集成、可选的开机启动和更新功能可能触发通用启发式警告。请仅从官方仓库下载，核对版本哈希，并报告意外检测结果以便调查。"],
    ["Questions, answered", "常见问题"], ["Before you install.", "安装之前。"], ["Does it work offline?", "可以离线使用吗？"], ["Yes, after installing the OCR language data and an Argos Translate or Hy-MT package for the direction you need. Online providers still require a connection.", "可以。你需要先安装 OCR 语言数据，以及所需翻译方向的 Argos Translate 或 Hy-MT 语言包。在线服务商仍然需要网络连接。"],
    ["Can it translate games and videos?", "可以翻译游戏和视频吗？"], ["Yes. OCR reads pixels from a selected region, so the source does not have to be selectable. Accuracy depends on the language, font, scale, contrast, and selected OCR engine.", "可以。OCR 读取所选区域的像素，因此原文无需能够选中。准确度取决于语言、字体、缩放、对比度和所选 OCR 引擎。"],
    ["Does it support Linux?", "支持 Linux 吗？"], ["Yes. The release page provides an x86_64 AppImage and a portable TAR archive. Screen capture integration may vary by desktop session.", "支持。版本页面提供 x86_64 AppImage 和便携式 TAR 压缩包。屏幕捕获集成可能因桌面会话而异。"],
    ["Can I change every hotkey?", "可以修改所有快捷键吗？"], ["Yes. Every global shortcut can be changed or cleared. OCR, full-screen, selection, replacement, and Dynamic translation remember their own language pair.", "可以。每个全局快捷键都能修改或清除。OCR、全屏、选中、替换和动态翻译模式会分别记住各自的语言对。"],
    ["What document formats are supported?", "支持哪些文档格式？"], ["TXT, Markdown, DOCX, PDF, HTML, HTM, and RTF. Results can be saved as text, Markdown, or a reopenable local session.", "支持 TXT、Markdown、DOCX、PDF、HTML、HTM 和 RTF。结果可保存为文本、Markdown，或可重新打开的本地会话。"],
    ["See it. Select it. Understand it.", "看见。选中。读懂。"], ["Translate the first thing that gets in your way.", "从第一段阻碍你的文字开始翻译。"], ["Download the latest Click'n'Translate", "下载最新版 Click'n'Translate"], ["Browse the source", "查看源代码"], ["Free and open-source screen OCR and translation.", "免费开源的屏幕 OCR 与翻译工具。"], ["Footer navigation", "页脚导航"], ["Downloads", "下载"], ["Bug reports", "错误报告"], ["License", "许可证"],
  ],
};

const languageMenu = (current, ariaLabel) => {
  const links = Object.entries(languageNames).map(([code, name]) => {
    const href = code === "en" ? "../" : `../${code}/`;
    const active = code === current ? ' class="active"' : "";
    return `            <a${active} href="${href}" lang="${code}" data-language-choice="${code}">${name}</a>`;
  }).join("\n");
  return `        <details class="language-menu">
          <summary aria-label="${ariaLabel}">${current === "zh-CN" ? "中文" : current.toUpperCase()}</summary>
          <div class="language-options">
${links}
          </div>
        </details>`;
};

const menuLabels = {
  es: "Elegir idioma",
  de: "Sprache wählen",
  fr: "Choisir la langue",
  "zh-CN": "选择语言",
};

const inlineRedirect = /\n    <script>\n      \(\(\) => \{[\s\S]*?\n    <\/script>(?=\n    <script type="application\/ld\+json">)/;

let template = await readFile(join(root, "index.html"), "utf8");

for (const [locale, replacements] of Object.entries(translations)) {
  let html = template.replace('<html lang="en">', `<html lang="${locale}">`);
  html = html.replace(inlineRedirect, "");
  for (const [source, target] of [...replacements].sort((a, b) => b[0].length - a[0].length)) {
    if (!html.includes(source)) throw new Error(`${locale}: source text not found: ${source}`);
    html = html.split(source).join(target);
  }

  const localeUrl = `${siteOrigin}/${locale}/`;
  html = html.replace(`<meta property="og:url" content="${siteOrigin}/" />`, `<meta property="og:url" content="${localeUrl}" />`);
  html = html.replace(`<link rel="canonical" href="${siteOrigin}/" />`, `<link rel="canonical" href="${localeUrl}" />`);
  html = html.replace(`"url": "${siteOrigin}/"`, `"url": "${localeUrl}"`);
  html = html.replace(/        <details class="language-menu">[\s\S]*?        <\/details>/, languageMenu(locale, menuLabels[locale]));
  html = html.replaceAll('href="assets/', 'href="../assets/');
  html = html.replaceAll('src="assets/', 'src="../assets/');
  html = html.replace('href="styles.css"', 'href="../styles.css"');
  html = html.replace('src="app.js"', 'src="../app.js"');

  const directory = join(root, locale);
  await mkdir(directory, { recursive: true });
  await writeFile(join(directory, "index.html"), html, "utf8");
}

console.log(`Generated ${Object.keys(translations).length} localized landing pages.`);
