"""Desktop companion copy, shared by Settings and the optional Qt widget."""

ASSISTANT_TEXT = {
    'en': {
        'tray': 'Desktop assistant', 'preview_hint': 'Configure the desktop assistant',
        'setting': 'Assistant:', 'enabled': 'On desktop', 'title': 'How can I help?',
        'hint': 'Click for translation actions. Drag to move the assistant.',
        'screen': ('Translate entire screen', 'Replace visible text with its translation.'),
        'area': ('Translate an area', 'Select the part of the screen to translate.'),
        'dynamic': ('Dynamic translation', 'Choose a source area and a separate output.'),
        'copy': ('Recognize and copy text', 'Select text on screen to copy it.'),
        'text': ('Open translator', 'Type, edit and translate text.'),
        'documents': ('Translate a document', 'Open a file or continue a saved session.'),
        'settings': 'Settings', 'guide': 'Quick guide', 'hide': 'Hide assistant',
        'hide_hint': 'Enable it again in General settings.', 'dismiss': 'Shoo', 'dismiss_hint': 'Hide the assistant until Click’n’Translate is restarted.',
    },
    'ru': {
        'tray': 'Помощник на рабочем столе', 'preview_hint': 'Настроить помощника на рабочем столе',
        'setting': 'Помощник:', 'enabled': 'На рабочем столе', 'title': 'Чем помочь?',
        'hint': 'Нажмите для выбора перевода. Перетащите помощника в удобное место.',
        'screen': ('Перевести весь экран', 'Заменить видимый текст его переводом.'),
        'area': ('Перевести область', 'Выберите часть экрана для перевода.'),
        'dynamic': ('Динамический перевод', 'Выберите источник и отдельное место вывода.'),
        'copy': ('Распознать и скопировать', 'Выберите текст на экране для копирования.'),
        'text': ('Открыть переводчик', 'Введите, дополните и переведите текст.'),
        'documents': ('Перевести документ', 'Откройте файл или сохранённую сессию.'),
        'settings': 'Настройки', 'guide': 'Обучение', 'hide': 'Скрыть помощника',
        'hide_hint': 'Включить снова можно в основных настройках.', 'dismiss': 'Прогнать', 'dismiss_hint': 'Скрыть помощника до следующего запуска Click’n’Translate.',
    },
    'de': {
        'tray': 'Desktop-Assistent', 'preview_hint': 'Desktop-Assistenten konfigurieren',
        'setting': 'Assistent:', 'enabled': 'Auf dem Desktop', 'title': 'Wie kann ich helfen?',
        'hint': 'Für Übersetzungsaktionen klicken. Zum Verschieben ziehen.',
        'screen': ('Gesamten Bildschirm übersetzen', 'Sichtbaren Text durch die Übersetzung ersetzen.'),
        'area': ('Bereich übersetzen', 'Den gewünschten Bildschirmbereich auswählen.'),
        'dynamic': ('Dynamische Übersetzung', 'Quelle und separaten Ausgabebereich wählen.'),
        'copy': ('Text erkennen und kopieren', 'Text auf dem Bildschirm zum Kopieren wählen.'),
        'text': ('Übersetzer öffnen', 'Text eingeben, bearbeiten und übersetzen.'),
        'documents': ('Dokument übersetzen', 'Datei oder gespeicherte Sitzung öffnen.'),
        'settings': 'Einstellungen', 'guide': 'Anleitung', 'hide': 'Assistent ausblenden',
        'hide_hint': 'In den allgemeinen Einstellungen wieder aktivieren.', 'dismiss': 'Wegschicken', 'dismiss_hint': 'Assistenten bis zum Neustart von Click’n’Translate ausblenden.',
    },
    'es': {
        'tray': 'Asistente de escritorio', 'preview_hint': 'Configurar el asistente de escritorio',
        'setting': 'Asistente:', 'enabled': 'En el escritorio', 'title': '¿Cómo puedo ayudar?',
        'hint': 'Haz clic para traducir. Arrastra el asistente para moverlo.',
        'screen': ('Traducir toda la pantalla', 'Sustituye el texto visible por su traducción.'),
        'area': ('Traducir un área', 'Selecciona la parte de la pantalla a traducir.'),
        'dynamic': ('Traducción dinámica', 'Elige el origen y un área de salida separada.'),
        'copy': ('Reconocer y copiar texto', 'Selecciona texto en pantalla para copiarlo.'),
        'text': ('Abrir traductor', 'Escribe, edita y traduce texto.'),
        'documents': ('Traducir un documento', 'Abre un archivo o una sesión guardada.'),
        'settings': 'Ajustes', 'guide': 'Guía', 'hide': 'Ocultar asistente',
        'hide_hint': 'Puedes activarlo de nuevo en los ajustes generales.', 'dismiss': 'Ahuyentar', 'dismiss_hint': 'Ocultar el asistente hasta reiniciar Click’n’Translate.',
    },
    'fr': {
        'tray': 'Assistant de bureau', 'preview_hint': 'Configurer l’assistant de bureau',
        'setting': 'Assistant :', 'enabled': 'Sur le bureau', 'title': 'Comment vous aider ?',
        'hint': 'Cliquez pour traduire. Faites glisser l’assistant pour le déplacer.',
        'screen': ('Traduire tout l’écran', 'Remplacer le texte visible par sa traduction.'),
        'area': ('Traduire une zone', 'Sélectionnez la partie de l’écran à traduire.'),
        'dynamic': ('Traduction dynamique', 'Choisissez la source et une zone de sortie.'),
        'copy': ('Reconnaître et copier le texte', 'Sélectionnez le texte à copier sur l’écran.'),
        'text': ('Ouvrir le traducteur', 'Saisissez, modifiez et traduisez du texte.'),
        'documents': ('Traduire un document', 'Ouvrez un fichier ou une session enregistrée.'),
        'settings': 'Réglages', 'guide': 'Guide', 'hide': 'Masquer l’assistant',
        'hide_hint': 'Réactivez-le dans les réglages généraux.', 'dismiss': 'Chasser', 'dismiss_hint': 'Masquer l’assistant jusqu’au redémarrage de Click’n’Translate.',
    },
    'zh': {
        'tray': '桌面助手', 'preview_hint': '设置桌面助手',
        'setting': '助手：', 'enabled': '在桌面显示', 'title': '需要什么帮助？',
        'hint': '点击选择翻译功能。拖动助手可调整位置。',
        'screen': ('翻译整个屏幕', '将可见文字替换为译文。'),
        'area': ('翻译区域', '选择需要翻译的屏幕区域。'),
        'dynamic': ('动态翻译', '分别选择识别区域和译文显示区域。'),
        'copy': ('识别并复制文字', '选择屏幕文字并复制。'),
        'text': ('打开翻译器', '输入、编辑并翻译文字。'),
        'documents': ('翻译文档', '打开文件或已保存的会话。'),
        'settings': '设置', 'guide': '使用指南', 'hide': '隐藏助手',
        'hide_hint': '可在常规设置中重新启用。', 'dismiss': '赶走', 'dismiss_hint': '隐藏助手，直到重新启动 Click’n’Translate。',
    },
}


def assistant_text(language, key):
    return ASSISTANT_TEXT.get(language, ASSISTANT_TEXT['en'])[key]
