"""Privacy-safe diagnostics for user initiated bug reports.

The report intentionally excludes clipboard contents, translation/copy history,
document text, API keys and the full configuration file.  A user can inspect
the generated ZIP before attaching it to GitHub or Telegram.
"""

from __future__ import annotations

import hashlib
import json
import os
import platform
import re
import sys
import tempfile
import time
import zipfile
from pathlib import Path


MAX_LOG_BYTES = 2 * 1024 * 1024
SAFE_CONFIG_KEYS = (
    "interface_language",
    "theme",
    "ocr_engine",
    "translator_engine",
    "start_in_shadow_mode",
    "show_window_after_selection",
    "show_window_after_ocr",
    "show_window_after_translation",
    "copy_translated_text",
    "keep_window_visible_during_ocr",
    "freeze_screen_on_ocr",
)


def _portable_root() -> Path:
    if getattr(sys, "frozen", False):
        executable = Path(sys.executable).resolve()
        # Installed/portable builds run from <root>/app/ClicknTranslateApp.exe.
        if executable.parent.name.lower() == "app":
            return executable.parent.parent
        return executable.parent
    return Path(__file__).resolve().parent


def _redactor() -> tuple[tuple[str, str], ...]:
    replacements: list[tuple[str, str]] = []
    values = {
        os.path.expanduser("~"),
        os.environ.get("USERPROFILE", ""),
        os.environ.get("APPDATA", ""),
        os.environ.get("LOCALAPPDATA", ""),
        tempfile.gettempdir(),
    }
    for value in sorted((item for item in values if item), key=len, reverse=True):
        replacements.append((os.path.normpath(value), "<user-path>"))
        replacements.append((os.path.normpath(value).replace("\\", "/"), "<user-path>"))
    username = os.environ.get("USERNAME") or os.environ.get("USER")
    if username:
        replacements.append((username, "<user>"))
    return tuple(replacements)


def _redact(value: object) -> str:
    text = str(value)
    for source, replacement in _redactor():
        text = re.sub(re.escape(source), replacement, text, flags=re.IGNORECASE)
    # Redact obvious bearer/API tokens that may have reached a third-party log.
    text = re.sub(
        r"(?i)(authorization\s*[:=]\s*bearer\s+|api[_-]?key\s*[:=]\s*)[^\s,;]+",
        r"\1<redacted>",
        text,
    )
    return text


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _file_line(label: str, path: Path) -> str:
    if not path.is_file():
        return f"{label}: missing ({_redact(path)})"
    try:
        stat = path.stat()
        return (
            f"{label}: present, bytes={stat.st_size}, "
            f"sha256={_sha256(path)}, path={_redact(path)}"
        )
    except OSError as error:
        return f"{label}: unreadable, path={_redact(path)}, error={_redact(error)}"


def _safe_config(data_root: Path) -> dict[str, object]:
    path = data_root / "config.json"
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except Exception as error:
        return {"config_status": f"unreadable: {_redact(error)}"}
    if not isinstance(payload, dict):
        return {"config_status": "not an object"}
    return {key: payload.get(key) for key in SAFE_CONFIG_KEYS if key in payload}


def _tail(path: Path, limit: int = MAX_LOG_BYTES) -> bytes:
    with path.open("rb") as source:
        source.seek(0, os.SEEK_END)
        size = source.tell()
        source.seek(max(0, size - limit))
        return source.read()


def _default_output_dir() -> Path:
    desktop = Path.home() / "Desktop"
    return desktop if desktop.is_dir() else Path(tempfile.gettempdir())


def create_bug_report(output_dir: str | os.PathLike[str] | None = None, *, app_version: str = "unknown") -> Path:
    """Create and return a local ZIP that is safe to share with maintainers."""

    root = _portable_root()
    data_root = root / "data"
    destination = Path(output_dir) if output_dir is not None else _default_output_dir()
    destination.mkdir(parents=True, exist_ok=True)
    stamp = time.strftime("%Y%m%d-%H%M%S")
    report_path = destination / f"ClicknTranslate-bug-report-{stamp}.zip"

    launcher = root / "ClicknTranslate.exe"
    inner = root / "app" / "ClicknTranslateApp.exe"
    updater = root / "app" / "_internal" / "ClicknTranslateUpdater.exe"
    lines = [
        "Click'n'Translate diagnostics",
        "Generated by an explicit user action; private text and histories are excluded.",
        "",
        f"generated_local: {time.strftime('%Y-%m-%d %H:%M:%S %z')}",
        f"app_version: {app_version}",
        f"platform: {_redact(platform.platform())}",
        f"windows_release: {_redact(platform.win32_ver())}",
        f"machine: {platform.machine()}",
        f"python: {platform.python_version()}",
        f"frozen: {bool(getattr(sys, 'frozen', False))}",
        f"root: {_redact(root)}",
        "",
        _file_line("public_launcher", launcher),
        _file_line("application", inner),
        _file_line("updater", updater),
        "",
        "safe_config:",
        json.dumps(_safe_config(data_root), ensure_ascii=False, indent=2, sort_keys=True),
    ]

    runtime_log = data_root / "logs" / "ocr_debug.log"
    if runtime_log.is_file():
        try:
            runtime_stat = runtime_log.stat()
            lines.extend([
                "",
                "runtime_log: present but intentionally excluded because OCR logs may contain recognized text",
                f"runtime_log_bytes: {runtime_stat.st_size}",
                f"runtime_log_modified_local: {time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(runtime_stat.st_mtime))}",
            ])
        except OSError:
            lines.extend(["", "runtime_log: present but unreadable and excluded"])

    log_candidates = [
        Path(tempfile.gettempdir()) / "clickntranslate_launcher.log",
        Path(tempfile.gettempdir()) / "clickntranslate_update.log",
        Path(tempfile.gettempdir()) / "clickntranslate_setup_update.log",
    ]
    with zipfile.ZipFile(report_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("report.txt", "\n".join(lines) + "\n")
        used_names: set[str] = set()
        for candidate in log_candidates:
            if not candidate.is_file():
                continue
            try:
                text = _tail(candidate).decode("utf-8", errors="replace")
                safe_text = _redact(text)
            except OSError as error:
                safe_text = f"Could not read log: {_redact(error)}\n"
            name = candidate.name
            if name in used_names:
                name = f"{candidate.parent.name}-{name}"
            used_names.add(name)
            archive.writestr(f"logs/{name}", safe_text)
    return report_path
